name: Bump version
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install node modules
        run: npm i conventional-changelog-angular
      - name: Bump version and push tag
        id: tag_version
        uses: ma4cek/tag-action@main
        # uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
